#!/usr/bin/env ruby


require 'logger'
require 'open-uri'
require 'pp'
require 'uri'

# this should be generated by merging together defaults and a configuration file
config = { 
  :graphite => { :url => 'http://localhost' },
  :collectd => { :prefix => "collectd", :postfix => nil, :escape_character => '_', :interval => 10 },
  :cpu => { :count => 8, :warning => 0.2, :critical => 0.4, :window => 60 },
  :verbose => true,
}

# this should be generated by command line arguments
config[:command] = 'cpu'
config[:host] = 'example.com'

config[:host].gsub!('.', config[:collectd][:escape_character])

logger = Logger.new(STDERR)
logger.level = config[:verbose] ? Logger::DEBUG : Logger::ERROR

def check_cpu(config,logger)
  warning = []
  critical = []

  # e.g if system has 4 CPUs range is 0 to 3
  range = (0..config[:cpu][:count]-1)

  # number of data points to average together
  samples = config[:cpu][:window] / config[:collectd][:interval]

  # Checking each cpu individually
  range.each do |i|
    # for each data point, add together the user and system time, then get an average of the data points
    url = URI.escape("#{config[:graphite][:url]}/render/?format=raw&target=movingAverage(sumSeries(#{config[:host]}.collectd.cpu-#{i}.cpu-{user,system}),#{samples})&from=-#{config[:cpu][:window]}seconds")
    logger.debug( URI.unescape(url) )
    response = open(url).read
    logger.debug(response)
    value = response.chomp!.rpartition(',').last.to_f
    if value >= config[:cpu][:warning] and value < config[:cpu][:critical]
      warning.push [i, value]
    elsif value >= config[:cpu][:critical]
      critical.push [i, value]
    end
  end

  if not critical.empty?
    output = 'CRITICAL: '
    code = 2
  elsif not warning.empty?
    output = 'WARNING: '
    code = 1
  else
    output = 'OK: CPU averages below threshholds'
    code = 0
  end

  critical.each { |c| output = output + "CPU #{c.first} averaged #{c.last}%. " }
  warning.each { |c| output = output + "CPU #{c.first} averaged #{c.last}%. " }

  puts output
  return code

end

case config[:command]
when 'cpu'
  check_cpu(config,logger)
else
  puts 'What kind of command is that?'
end

